export { Grid } from './grid'
export { TopFrame } from './grid-frame/top-frame'
export { BottomFrame, type BottomFrameLabel } from './grid-frame/bottom-frame'
export type { GridProps, GridStylesNames } from './grid'
export type { TopFrameProps, TopFrameStylesNames } from './grid-frame/top-frame'
export type { BottomFrameProps, BottomFrameStylesNames } from './grid-frame/bottom-frame'
