import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import openapiTS, { astToString, COMMENT_HEADER } from "openapi-typescript";

import { indexFileName, openapiFileName, schemaFileName } from "./constants";
import { extractBaseUrlFromSpec, formatSpec } from "./spec";

export const getOutputPaths = (outputDir: string) => ({
  openapi: join(outputDir, openapiFileName),
  schema: join(outputDir, schemaFileName),
  index: join(outputDir, indexFileName),
});

export const writeOpenApiSpec = (
  outputDir: string,
  spec: unknown,
): { changed: boolean; path: string } => {
  const { openapi: outputPath } = getOutputPaths(outputDir);
  const formattedSpec = formatSpec(spec);

  try {
    const existingSpec = readFileSync(outputPath, "utf8");
    if (existingSpec === formattedSpec) {
      return { changed: false, path: outputPath };
    }
  } catch {
    // File does not exist yet.
  }

  writeFileSync(outputPath, formattedSpec, "utf8");
  return { changed: true, path: outputPath };
};

export const generateSchema = async (outputDir: string): Promise<string> => {
  const { openapi, schema } = getOutputPaths(outputDir);
  const nodes = await openapiTS(pathToFileURL(openapi));
  writeFileSync(schema, `${COMMENT_HEADER}${astToString(nodes)}`, "utf8");
  return schema;
};

export const generateIndexTs = (
  spec: Record<string, unknown>,
  fallbackBaseUrl: string,
): string => {
  const { baseUrl, usedFallback } = extractBaseUrlFromSpec(
    spec,
    fallbackBaseUrl,
  );

  if (usedFallback) {
    console.warn(
      `No servers[0].url found in OpenAPI spec; using fallback baseUrl ${fallbackBaseUrl}.`,
    );
  }

  return `// Generated by @eve-online-tools/esi-provider — safe to edit.
// Re-run download-spec only updates openapi.json / esi-schema.d.ts / compatibility-date.ts.

import {
  createESIProvider as internalCreateESIProvider,
  type CreateProviderResult,
  type NewProviderProps,
} from "@eve-online-tools/esi-provider";
import compatibilityDate from "./compatibility-date";
import type { paths } from "./esi-schema";

export type { paths, operations } from "./esi-schema";
export { default as compatibilityDate } from "./compatibility-date";

const baseUrl = "${baseUrl}";

/** Pre-configured ESI provider factory for this project's generated schema. */
export const createESIProvider = (
  props: NewProviderProps,
): CreateProviderResult<paths> =>
  internalCreateESIProvider<paths>({
    baseUrl,
    compatibilityDate,
    ...props,
  });
`;
};

export const ensureIndexTs = (
  outputDir: string,
  spec: Record<string, unknown>,
  fallbackBaseUrl: string,
): { created: boolean; path: string } => {
  const { index } = getOutputPaths(outputDir);

  if (existsSync(index)) {
    return { created: false, path: index };
  }

  writeFileSync(index, generateIndexTs(spec, fallbackBaseUrl), "utf8");
  return { created: true, path: index };
};
