import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import openapiTS, { astToString, COMMENT_HEADER } from "openapi-typescript";

import {
  indexFileName,
  openapiFileName,
  schemaFileName,
  typesFileName,
} from "./constants";
import { extractBaseUrlFromSpec, formatSpec } from "./spec";

export const getOutputPaths = (outputDir: string) => ({
  openapi: join(outputDir, openapiFileName),
  schema: join(outputDir, schemaFileName),
  types: join(outputDir, typesFileName),
  index: join(outputDir, indexFileName),
});

export const writeOpenApiSpec = (
  outputDir: string,
  spec: unknown,
): { changed: boolean; path: string } => {
  const { openapi: outputPath } = getOutputPaths(outputDir);
  const formattedSpec = formatSpec(spec);

  try {
    const existingSpec = readFileSync(outputPath, "utf8");
    if (existingSpec === formattedSpec) {
      return { changed: false, path: outputPath };
    }
  } catch {
    // File does not exist yet.
  }

  writeFileSync(outputPath, formattedSpec, "utf8");
  return { changed: true, path: outputPath };
};

export const generateSchema = async (
  outputDir: string,
): Promise<{ schemaPath: string; typesPath: string }> => {
  const { openapi, schema, types } = getOutputPaths(outputDir);
  const nodes = await openapiTS(pathToFileURL(openapi));
  writeFileSync(schema, `${COMMENT_HEADER}${astToString(nodes)}`, "utf8");
  writeFileSync(types, generateTypesDts(), "utf8");
  return { schemaPath: schema, typesPath: types };
};

export const generateTypesDts =
  (): string => `import type { Client as BaseClient } from "openapi-fetch";
import type { operations, paths } from "./esi-schema";

type HttpMethod = "get" | "put" | "post" | "delete" | "options" | "head" | "patch" | "trace";

type Operation = operations[keyof operations];

type JsonBody<TResponse> = TResponse extends { content: infer TContent }
  ? TContent extends { "application/json": infer TBody }
    ? TBody
    : never
  : never;

type DefaultOkStatus<R> = 200 extends keyof R ? 200 : keyof R;

export type MethodsForPath<TPath extends keyof paths> = {
  [M in HttpMethod]: paths[TPath][M] extends Operation ? M : never;
}[HttpMethod];

export type OperationFor<
  TPath extends keyof paths,
  TMethod extends MethodsForPath<TPath>,
> = Extract<paths[TPath][TMethod], Operation>;

export type ResponseFor<
  TPath extends keyof paths,
  TMethod extends MethodsForPath<TPath>,
  TStatus extends keyof OperationFor<TPath, TMethod>["responses"] = DefaultOkStatus<
    OperationFor<TPath, TMethod>["responses"]
  >,
> = JsonBody<OperationFor<TPath, TMethod>["responses"][TStatus]>;

export type ResponseForOperation<
  TOperation extends keyof operations,
  TStatus extends keyof operations[TOperation]["responses"] = DefaultOkStatus<
    operations[TOperation]["responses"]
  >,
> = JsonBody<operations[TOperation]["responses"][TStatus]>;

export type Client = BaseClient<paths, "application/json">;
`;

export const generateIndexTs = (
  spec: Record<string, unknown>,
  fallbackBaseUrl: string,
): string => {
  const { baseUrl, usedFallback } = extractBaseUrlFromSpec(
    spec,
    fallbackBaseUrl,
  );

  if (usedFallback) {
    console.warn(
      `No servers[0].url found in OpenAPI spec; using fallback baseUrl ${fallbackBaseUrl}.`,
    );
  }

  return `// Generated by @eve-online-tools/esi-provider — safe to edit.
// Re-run download-spec only updates openapi.json / esi-schema.d.ts / types.d.ts / compatibility-date.ts.

import {
  createESIProvider as internalCreateESIProvider,
  type CreateProviderResult,
  type NewProviderProps,
} from "@eve-online-tools/esi-provider";
import compatibilityDate from "./compatibility-date";
import type { paths } from "./esi-schema";

export type { paths, components, operations } from "./esi-schema";
export type {
  Client,
  MethodsForPath,
  OperationFor,
  ResponseFor,
  ResponseForOperation,
} from "./types";
export { default as compatibilityDate } from "./compatibility-date";

const baseUrl = "${baseUrl}";

/** Pre-configured ESI provider factory for this project's generated schema. */
export const createESIProvider = (
  props: NewProviderProps,
): CreateProviderResult<paths> =>
  internalCreateESIProvider<paths>({
    baseUrl,
    compatibilityDate,
    ...props,
  });
`;
};

export const ensureIndexTs = (
  outputDir: string,
  spec: Record<string, unknown>,
  fallbackBaseUrl: string,
): { created: boolean; path: string } => {
  const { index } = getOutputPaths(outputDir);

  if (existsSync(index)) {
    return { created: false, path: index };
  }

  writeFileSync(index, generateIndexTs(spec, fallbackBaseUrl), "utf8");
  return { created: true, path: index };
};
